/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type {
	AuthInfo,
	Error,
	RegisterData,
	SuccessfulResult,
	User,
} from '../model';

import authLoginPOSTMutator from '../../lib/mutator';
import authLogoutGETMutator from '../../lib/mutator';
import userPOSTMutator from '../../lib/mutator';
import profileGETMutator from '../../lib/mutator';

export type authLoginPOSTResponse200 = {
	data: SuccessfulResult;
	status: 200;
};

export type authLoginPOSTResponse400 = {
	data: void;
	status: 400;
};

export type authLoginPOSTResponseSuccess = authLoginPOSTResponse200 & {
	headers: Headers;
};
export type authLoginPOSTResponseError = authLoginPOSTResponse400 & {
	headers: Headers;
};

export type authLoginPOSTResponse =
	| authLoginPOSTResponseSuccess
	| authLoginPOSTResponseError;

export const getAuthLoginPOSTUrl = () => {
	return `/auth/login`;
};

/**
 * Принимает адрес почты:пароль, открывает новую пользовательскую сессию
 * @summary Логин пользователя по почте:паролю
 */
export const authLoginPOST = async (
	authInfo: AuthInfo,
	options?: RequestInit,
): Promise<authLoginPOSTResponse> => {
	const formUrlEncoded = new URLSearchParams();
	formUrlEncoded.append(`email`, authInfo.email);
	formUrlEncoded.append(`password`, authInfo.password);

	return authLoginPOSTMutator<authLoginPOSTResponse>(getAuthLoginPOSTUrl(), {
		...options,
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options?.headers,
		},
		body: formUrlEncoded,
	});
};

export const getAuthLoginPOSTMutationOptions = <
	TError = void,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof authLoginPOST>>,
		TError,
		{ data: AuthInfo },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof authLoginPOST>>,
	TError,
	{ data: AuthInfo },
	TContext
> => {
	const mutationKey = ['authLoginPOST'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof authLoginPOST>>,
		{ data: AuthInfo }
	> = (props) => {
		const { data } = props ?? {};

		return authLoginPOST(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type AuthLoginPOSTMutationResult = NonNullable<
	Awaited<ReturnType<typeof authLoginPOST>>
>;
export type AuthLoginPOSTMutationBody = AuthInfo;
export type AuthLoginPOSTMutationError = void;

/**
 * @summary Логин пользователя по почте:паролю
 */
export const useAuthLoginPOST = <TError = void, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof authLoginPOST>>,
			TError,
			{ data: AuthInfo },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof authLoginPOST>>,
	TError,
	{ data: AuthInfo },
	TContext
> => {
	return useMutation(getAuthLoginPOSTMutationOptions(options), queryClient);
};
export type authLogoutGETResponse200 = {
	data: SuccessfulResult;
	status: 200;
};

export type authLogoutGETResponseSuccess = authLogoutGETResponse200 & {
	headers: Headers;
};
export type authLogoutGETResponse = authLogoutGETResponseSuccess;

export const getAuthLogoutGETUrl = () => {
	return `/auth/logout`;
};

/**
 * @summary Закрытие текущей пользовательской сессии
 */
export const authLogoutGET = async (
	options?: RequestInit,
): Promise<authLogoutGETResponse> => {
	return authLogoutGETMutator<authLogoutGETResponse>(getAuthLogoutGETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getAuthLogoutGETQueryKey = () => {
	return [`/auth/logout`] as const;
};

export const getAuthLogoutGETQueryOptions = <
	TData = Awaited<ReturnType<typeof authLogoutGET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof authLogoutGET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getAuthLogoutGETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof authLogoutGET>>> = ({
		signal,
	}) => authLogoutGET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof authLogoutGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthLogoutGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof authLogoutGET>>
>;
export type AuthLogoutGETQueryError = unknown;

export function useAuthLogoutGET<
	TData = Awaited<ReturnType<typeof authLogoutGET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authLogoutGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof authLogoutGET>>,
					TError,
					Awaited<ReturnType<typeof authLogoutGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthLogoutGET<
	TData = Awaited<ReturnType<typeof authLogoutGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authLogoutGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof authLogoutGET>>,
					TError,
					Awaited<ReturnType<typeof authLogoutGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthLogoutGET<
	TData = Awaited<ReturnType<typeof authLogoutGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authLogoutGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Закрытие текущей пользовательской сессии
 */

export function useAuthLogoutGET<
	TData = Awaited<ReturnType<typeof authLogoutGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof authLogoutGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getAuthLogoutGETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type userPOSTResponse200 = {
	data: SuccessfulResult;
	status: 200;
};

export type userPOSTResponse400 = {
	data: Error;
	status: 400;
};

export type userPOSTResponseSuccess = userPOSTResponse200 & {
	headers: Headers;
};
export type userPOSTResponseError = userPOSTResponse400 & {
	headers: Headers;
};

export type userPOSTResponse = userPOSTResponseSuccess | userPOSTResponseError;

export const getUserPOSTUrl = () => {
	return `/user`;
};

/**
 * @summary Регистрация/Создание пользователя
 */
export const userPOST = async (
	registerData?: RegisterData,
	options?: RequestInit,
): Promise<userPOSTResponse> => {
	const formUrlEncoded = new URLSearchParams();
	formUrlEncoded.append('data', registerData);

	return userPOSTMutator<userPOSTResponse>(getUserPOSTUrl(), {
		...options,
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options?.headers,
		},
		body: formUrlEncoded,
	});
};

export const getUserPOSTMutationOptions = <
	TError = Error,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof userPOST>>,
		TError,
		{ data?: RegisterData },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof userPOST>>,
	TError,
	{ data?: RegisterData },
	TContext
> => {
	const mutationKey = ['userPOST'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof userPOST>>,
		{ data?: RegisterData }
	> = (props) => {
		const { data } = props ?? {};

		return userPOST(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type UserPOSTMutationResult = NonNullable<
	Awaited<ReturnType<typeof userPOST>>
>;
export type UserPOSTMutationBody = RegisterData | undefined;
export type UserPOSTMutationError = Error;

/**
 * @summary Регистрация/Создание пользователя
 */
export const useUserPOST = <TError = Error, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof userPOST>>,
			TError,
			{ data?: RegisterData },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof userPOST>>,
	TError,
	{ data?: RegisterData },
	TContext
> => {
	return useMutation(getUserPOSTMutationOptions(options), queryClient);
};
export type profileGETResponse200 = {
	data: User;
	status: 200;
};

export type profileGETResponseSuccess = profileGETResponse200 & {
	headers: Headers;
};
export type profileGETResponse = profileGETResponseSuccess;

export const getProfileGETUrl = () => {
	return `/profile`;
};

/**
 * @summary Получение данных о текущем авторизованном пользователе
 */
export const profileGET = async (
	options?: RequestInit,
): Promise<profileGETResponse> => {
	return profileGETMutator<profileGETResponse>(getProfileGETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getProfileGETQueryKey = () => {
	return [`/profile`] as const;
};

export const getProfileGETQueryOptions = <
	TData = Awaited<ReturnType<typeof profileGET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof profileGET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getProfileGETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof profileGET>>> = ({
		signal,
	}) => profileGET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof profileGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof profileGET>>
>;
export type ProfileGETQueryError = unknown;

export function useProfileGET<
	TData = Awaited<ReturnType<typeof profileGET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof profileGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof profileGET>>,
					TError,
					Awaited<ReturnType<typeof profileGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileGET<
	TData = Awaited<ReturnType<typeof profileGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof profileGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof profileGET>>,
					TError,
					Awaited<ReturnType<typeof profileGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileGET<
	TData = Awaited<ReturnType<typeof profileGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof profileGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение данных о текущем авторизованном пользователе
 */

export function useProfileGET<
	TData = Awaited<ReturnType<typeof profileGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof profileGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getProfileGETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
