/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import type { SuccessfulResult, User } from '../model';

export const getAuthLoginPOSTResponseMock = (
	overrideResponse: Partial<Extract<SuccessfulResult, object>> = {},
): SuccessfulResult => ({
	result: faker.datatype.boolean(),
	...overrideResponse,
});

export const getAuthLogoutGETResponseMock = (
	overrideResponse: Partial<Extract<SuccessfulResult, object>> = {},
): SuccessfulResult => ({
	result: faker.datatype.boolean(),
	...overrideResponse,
});

export const getUserPOSTResponseMock = (
	overrideResponse: Partial<Extract<SuccessfulResult, object>> = {},
): SuccessfulResult => ({
	result: faker.datatype.boolean(),
	...overrideResponse,
});

export const getProfileGETResponseMock = (
	overrideResponse: Partial<Extract<User, object>> = {},
): User => ({
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	surname: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	email: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	favorites: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
		undefined,
	]),
	...overrideResponse,
});
