/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Получение фильмов по заданным фильтрам
 */
export const MovieGETQueryParams = zod.object({
	count: zod
		.number()
		.optional()
		.describe(
			'ограничение количества возвращаемых фильмов (по-умолчанию - 50)',
		),
	page: zod
		.number()
		.optional()
		.describe('показ следующей страницы списка фильмов'),
	title: zod.string().optional().describe('фильтр по названию фильма'),
	genre: zod.string().optional().describe('фильтр по жанру'),
});

export const MovieGETResponseItem = zod.object({
	id: zod.number().optional(),
	title: zod.string().optional(),
	originalTitle: zod.string().optional(),
	language: zod.string().optional(),
	releaseYear: zod.number().optional(),
	releaseDate: zod.string().optional(),
	genres: zod.array(zod.string()).optional(),
	plot: zod.string().optional(),
	runtime: zod.number().optional(),
	budget: zod.string().optional(),
	revenue: zod.string().optional(),
	homepage: zod.string().optional(),
	status: zod.string().optional(),
	posterUrl: zod.string().optional(),
	backdropUrl: zod.string().optional(),
	trailerUrl: zod.string().optional(),
	trailerYouTubeId: zod.string().optional(),
	tmdbRating: zod.number().optional(),
	searchL: zod.string().optional(),
	keywords: zod.array(zod.string()).optional(),
	countriesOfOrigin: zod.array(zod.string()).optional(),
	languages: zod.array(zod.string()).optional(),
	cast: zod.array(zod.string()).optional(),
	director: zod.string().optional(),
	production: zod.string().optional(),
	awardsSummary: zod.string().optional(),
});
export const MovieGETResponse = zod.array(MovieGETResponseItem);

/**
 * @summary Получение фильмов с наивысшим рейтингом
 */
export const MovieTop10GETResponseItem = zod.object({
	id: zod.number().optional(),
	title: zod.string().optional(),
	originalTitle: zod.string().optional(),
	language: zod.string().optional(),
	releaseYear: zod.number().optional(),
	releaseDate: zod.string().optional(),
	genres: zod.array(zod.string()).optional(),
	plot: zod.string().optional(),
	runtime: zod.number().optional(),
	budget: zod.string().optional(),
	revenue: zod.string().optional(),
	homepage: zod.string().optional(),
	status: zod.string().optional(),
	posterUrl: zod.string().optional(),
	backdropUrl: zod.string().optional(),
	trailerUrl: zod.string().optional(),
	trailerYouTubeId: zod.string().optional(),
	tmdbRating: zod.number().optional(),
	searchL: zod.string().optional(),
	keywords: zod.array(zod.string()).optional(),
	countriesOfOrigin: zod.array(zod.string()).optional(),
	languages: zod.array(zod.string()).optional(),
	cast: zod.array(zod.string()).optional(),
	director: zod.string().optional(),
	production: zod.string().optional(),
	awardsSummary: zod.string().optional(),
});
export const MovieTop10GETResponse = zod.array(MovieTop10GETResponseItem);

/**
 * @summary Получение жанров
 */
export const MovieGenresGETResponseItem = zod.string();
export const MovieGenresGETResponse = zod.array(MovieGenresGETResponseItem);

/**
 * @summary Получение фильма по id
 */
export const MovieIdGETParams = zod.object({
	movieId: zod.number().describe('ID фильма'),
});

export const MovieIdGETResponse = zod.object({
	id: zod.number().optional(),
	title: zod.string().optional(),
	originalTitle: zod.string().optional(),
	language: zod.string().optional(),
	releaseYear: zod.number().optional(),
	releaseDate: zod.string().optional(),
	genres: zod.array(zod.string()).optional(),
	plot: zod.string().optional(),
	runtime: zod.number().optional(),
	budget: zod.string().optional(),
	revenue: zod.string().optional(),
	homepage: zod.string().optional(),
	status: zod.string().optional(),
	posterUrl: zod.string().optional(),
	backdropUrl: zod.string().optional(),
	trailerUrl: zod.string().optional(),
	trailerYouTubeId: zod.string().optional(),
	tmdbRating: zod.number().optional(),
	searchL: zod.string().optional(),
	keywords: zod.array(zod.string()).optional(),
	countriesOfOrigin: zod.array(zod.string()).optional(),
	languages: zod.array(zod.string()).optional(),
	cast: zod.array(zod.string()).optional(),
	director: zod.string().optional(),
	production: zod.string().optional(),
	awardsSummary: zod.string().optional(),
});

/**
 * @summary Получение случайного фильма
 */
export const MovieRandomGETResponse = zod.object({
	id: zod.number().optional(),
	title: zod.string().optional(),
	originalTitle: zod.string().optional(),
	language: zod.string().optional(),
	releaseYear: zod.number().optional(),
	releaseDate: zod.string().optional(),
	genres: zod.array(zod.string()).optional(),
	plot: zod.string().optional(),
	runtime: zod.number().optional(),
	budget: zod.string().optional(),
	revenue: zod.string().optional(),
	homepage: zod.string().optional(),
	status: zod.string().optional(),
	posterUrl: zod.string().optional(),
	backdropUrl: zod.string().optional(),
	trailerUrl: zod.string().optional(),
	trailerYouTubeId: zod.string().optional(),
	tmdbRating: zod.number().optional(),
	searchL: zod.string().optional(),
	keywords: zod.array(zod.string()).optional(),
	countriesOfOrigin: zod.array(zod.string()).optional(),
	languages: zod.array(zod.string()).optional(),
	cast: zod.array(zod.string()).optional(),
	director: zod.string().optional(),
	production: zod.string().optional(),
	awardsSummary: zod.string().optional(),
});
