/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { Movie, MovieGETParams } from '../model';

import movieGETMutator from '../../lib/mutator';
import movieTop10GETMutator from '../../lib/mutator';
import movieGenresGETMutator from '../../lib/mutator';
import movieIdGETMutator from '../../lib/mutator';
import movieRandomGETMutator from '../../lib/mutator';

export type movieGETResponse200 = {
	data: Movie[];
	status: 200;
};

export type movieGETResponseSuccess = movieGETResponse200 & {
	headers: Headers;
};
export type movieGETResponse = movieGETResponseSuccess;

export const getMovieGETUrl = (params?: MovieGETParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? 'null' : String(value));
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/movie?${stringifiedParams}`
		: `/movie`;
};

/**
 * @summary Получение фильмов по заданным фильтрам
 */
export const movieGET = async (
	params?: MovieGETParams,
	options?: RequestInit,
): Promise<movieGETResponse> => {
	return movieGETMutator<movieGETResponse>(getMovieGETUrl(params), {
		...options,
		method: 'GET',
	});
};

export const getMovieGETQueryKey = (params?: MovieGETParams) => {
	return [`/movie`, ...(params ? [params] : [])] as const;
};

export const getMovieGETQueryOptions = <
	TData = Awaited<ReturnType<typeof movieGET>>,
	TError = unknown,
>(
	params?: MovieGETParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGET>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMovieGETQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof movieGET>>> = ({
		signal,
	}) => movieGET(params, { signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof movieGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovieGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof movieGET>>
>;
export type MovieGETQueryError = unknown;

export function useMovieGET<
	TData = Awaited<ReturnType<typeof movieGET>>,
	TError = unknown,
>(
	params: undefined | MovieGETParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieGET>>,
					TError,
					Awaited<ReturnType<typeof movieGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieGET<
	TData = Awaited<ReturnType<typeof movieGET>>,
	TError = unknown,
>(
	params?: MovieGETParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieGET>>,
					TError,
					Awaited<ReturnType<typeof movieGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieGET<
	TData = Awaited<ReturnType<typeof movieGET>>,
	TError = unknown,
>(
	params?: MovieGETParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение фильмов по заданным фильтрам
 */

export function useMovieGET<
	TData = Awaited<ReturnType<typeof movieGET>>,
	TError = unknown,
>(
	params?: MovieGETParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMovieGETQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type movieTop10GETResponse200 = {
	data: Movie[];
	status: 200;
};

export type movieTop10GETResponseSuccess = movieTop10GETResponse200 & {
	headers: Headers;
};
export type movieTop10GETResponse = movieTop10GETResponseSuccess;

export const getMovieTop10GETUrl = () => {
	return `/movie/top10`;
};

/**
 * @summary Получение фильмов с наивысшим рейтингом
 */
export const movieTop10GET = async (
	options?: RequestInit,
): Promise<movieTop10GETResponse> => {
	return movieTop10GETMutator<movieTop10GETResponse>(getMovieTop10GETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getMovieTop10GETQueryKey = () => {
	return [`/movie/top10`] as const;
};

export const getMovieTop10GETQueryOptions = <
	TData = Awaited<ReturnType<typeof movieTop10GET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof movieTop10GET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMovieTop10GETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof movieTop10GET>>> = ({
		signal,
	}) => movieTop10GET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof movieTop10GET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovieTop10GETQueryResult = NonNullable<
	Awaited<ReturnType<typeof movieTop10GET>>
>;
export type MovieTop10GETQueryError = unknown;

export function useMovieTop10GET<
	TData = Awaited<ReturnType<typeof movieTop10GET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieTop10GET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieTop10GET>>,
					TError,
					Awaited<ReturnType<typeof movieTop10GET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieTop10GET<
	TData = Awaited<ReturnType<typeof movieTop10GET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieTop10GET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieTop10GET>>,
					TError,
					Awaited<ReturnType<typeof movieTop10GET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieTop10GET<
	TData = Awaited<ReturnType<typeof movieTop10GET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieTop10GET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение фильмов с наивысшим рейтингом
 */

export function useMovieTop10GET<
	TData = Awaited<ReturnType<typeof movieTop10GET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieTop10GET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMovieTop10GETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type movieGenresGETResponse200 = {
	data: string[];
	status: 200;
};

export type movieGenresGETResponseSuccess = movieGenresGETResponse200 & {
	headers: Headers;
};
export type movieGenresGETResponse = movieGenresGETResponseSuccess;

export const getMovieGenresGETUrl = () => {
	return `/movie/genres`;
};

/**
 * @summary Получение жанров
 */
export const movieGenresGET = async (
	options?: RequestInit,
): Promise<movieGenresGETResponse> => {
	return movieGenresGETMutator<movieGenresGETResponse>(getMovieGenresGETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getMovieGenresGETQueryKey = () => {
	return [`/movie/genres`] as const;
};

export const getMovieGenresGETQueryOptions = <
	TData = Awaited<ReturnType<typeof movieGenresGET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof movieGenresGET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMovieGenresGETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof movieGenresGET>>> = ({
		signal,
	}) => movieGenresGET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof movieGenresGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovieGenresGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof movieGenresGET>>
>;
export type MovieGenresGETQueryError = unknown;

export function useMovieGenresGET<
	TData = Awaited<ReturnType<typeof movieGenresGET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGenresGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieGenresGET>>,
					TError,
					Awaited<ReturnType<typeof movieGenresGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieGenresGET<
	TData = Awaited<ReturnType<typeof movieGenresGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGenresGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieGenresGET>>,
					TError,
					Awaited<ReturnType<typeof movieGenresGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieGenresGET<
	TData = Awaited<ReturnType<typeof movieGenresGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGenresGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение жанров
 */

export function useMovieGenresGET<
	TData = Awaited<ReturnType<typeof movieGenresGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieGenresGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMovieGenresGETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type movieIdGETResponse200 = {
	data: Movie;
	status: 200;
};

export type movieIdGETResponseSuccess = movieIdGETResponse200 & {
	headers: Headers;
};
export type movieIdGETResponse = movieIdGETResponseSuccess;

export const getMovieIdGETUrl = (movieId: number) => {
	return `/movie/${movieId}`;
};

/**
 * @summary Получение фильма по id
 */
export const movieIdGET = async (
	movieId: number,
	options?: RequestInit,
): Promise<movieIdGETResponse> => {
	return movieIdGETMutator<movieIdGETResponse>(getMovieIdGETUrl(movieId), {
		...options,
		method: 'GET',
	});
};

export const getMovieIdGETQueryKey = (movieId: number) => {
	return [`/movie/${movieId}`] as const;
};

export const getMovieIdGETQueryOptions = <
	TData = Awaited<ReturnType<typeof movieIdGET>>,
	TError = unknown,
>(
	movieId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieIdGET>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMovieIdGETQueryKey(movieId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof movieIdGET>>> = ({
		signal,
	}) => movieIdGET(movieId, { signal });

	return {
		queryKey,
		queryFn,
		enabled: movieId !== null && movieId !== undefined,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof movieIdGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovieIdGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof movieIdGET>>
>;
export type MovieIdGETQueryError = unknown;

export function useMovieIdGET<
	TData = Awaited<ReturnType<typeof movieIdGET>>,
	TError = unknown,
>(
	movieId: number,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieIdGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieIdGET>>,
					TError,
					Awaited<ReturnType<typeof movieIdGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieIdGET<
	TData = Awaited<ReturnType<typeof movieIdGET>>,
	TError = unknown,
>(
	movieId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieIdGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieIdGET>>,
					TError,
					Awaited<ReturnType<typeof movieIdGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieIdGET<
	TData = Awaited<ReturnType<typeof movieIdGET>>,
	TError = unknown,
>(
	movieId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieIdGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение фильма по id
 */

export function useMovieIdGET<
	TData = Awaited<ReturnType<typeof movieIdGET>>,
	TError = unknown,
>(
	movieId: number,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieIdGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMovieIdGETQueryOptions(movieId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type movieRandomGETResponse200 = {
	data: Movie;
	status: 200;
};

export type movieRandomGETResponseSuccess = movieRandomGETResponse200 & {
	headers: Headers;
};
export type movieRandomGETResponse = movieRandomGETResponseSuccess;

export const getMovieRandomGETUrl = () => {
	return `/movie/random`;
};

/**
 * @summary Получение случайного фильма
 */
export const movieRandomGET = async (
	options?: RequestInit,
): Promise<movieRandomGETResponse> => {
	return movieRandomGETMutator<movieRandomGETResponse>(getMovieRandomGETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getMovieRandomGETQueryKey = () => {
	return [`/movie/random`] as const;
};

export const getMovieRandomGETQueryOptions = <
	TData = Awaited<ReturnType<typeof movieRandomGET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof movieRandomGET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getMovieRandomGETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof movieRandomGET>>> = ({
		signal,
	}) => movieRandomGET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof movieRandomGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MovieRandomGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof movieRandomGET>>
>;
export type MovieRandomGETQueryError = unknown;

export function useMovieRandomGET<
	TData = Awaited<ReturnType<typeof movieRandomGET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieRandomGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieRandomGET>>,
					TError,
					Awaited<ReturnType<typeof movieRandomGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieRandomGET<
	TData = Awaited<ReturnType<typeof movieRandomGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieRandomGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof movieRandomGET>>,
					TError,
					Awaited<ReturnType<typeof movieRandomGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useMovieRandomGET<
	TData = Awaited<ReturnType<typeof movieRandomGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieRandomGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение случайного фильма
 */

export function useMovieRandomGET<
	TData = Awaited<ReturnType<typeof movieRandomGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof movieRandomGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getMovieRandomGETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
