/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Получение избранных фильмов
 */
export const FavoritesGETResponseItem = zod.object({
	id: zod.number().optional(),
	title: zod.string().optional(),
	originalTitle: zod.string().optional(),
	language: zod.string().optional(),
	releaseYear: zod.number().optional(),
	releaseDate: zod.string().optional(),
	genres: zod.array(zod.string()).optional(),
	plot: zod.string().optional(),
	runtime: zod.number().optional(),
	budget: zod.string().optional(),
	revenue: zod.string().optional(),
	homepage: zod.string().optional(),
	status: zod.string().optional(),
	posterUrl: zod.string().optional(),
	backdropUrl: zod.string().optional(),
	trailerUrl: zod.string().optional(),
	trailerYouTubeId: zod.string().optional(),
	tmdbRating: zod.number().optional(),
	searchL: zod.string().optional(),
	keywords: zod.array(zod.string()).optional(),
	countriesOfOrigin: zod.array(zod.string()).optional(),
	languages: zod.array(zod.string()).optional(),
	cast: zod.array(zod.string()).optional(),
	director: zod.string().optional(),
	production: zod.string().optional(),
	awardsSummary: zod.string().optional(),
});
export const FavoritesGETResponse = zod.array(FavoritesGETResponseItem);

/**
 * @summary Добавление фильма в избранное
 */
export const FavoritesPOSTResponse = zod.object({
	name: zod.string().optional(),
	surname: zod.string().optional(),
	email: zod.string().optional(),
	favorites: zod
		.array(zod.string())
		.optional()
		.describe('Массив с ID фильмов добавленными в избранное'),
});

/**
 * @summary Удаление фильма из избранного
 */
export const FavoritesMovieIdDELETEParams = zod.object({
	movieId: zod.number().describe('ID фильма'),
});

export const FavoritesMovieIdDELETEResponse = zod.object({
	name: zod.string().optional(),
	surname: zod.string().optional(),
	email: zod.string().optional(),
	favorites: zod
		.array(zod.string())
		.optional()
		.describe('Массив с ID фильмов добавленными в избранное'),
});
