/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Принимает адрес почты:пароль, открывает новую пользовательскую сессию
 * @summary Логин пользователя по почте:паролю
 */
export const AuthLoginPOSTResponse = zod.object({
	result: zod.boolean(),
});

/**
 * @summary Закрытие текущей пользовательской сессии
 */
export const AuthLogoutGETResponse = zod.object({
	result: zod.boolean(),
});

/**
 * @summary Регистрация/Создание пользователя
 */
export const UserPOSTResponse = zod.object({
	result: zod.boolean(),
});

/**
 * @summary Получение данных о текущем авторизованном пользователе
 */
export const ProfileGETResponse = zod.object({
	name: zod.string().optional(),
	surname: zod.string().optional(),
	email: zod.string().optional(),
	favorites: zod
		.array(zod.string())
		.optional()
		.describe('Массив с ID фильмов добавленными в избранное'),
});
