/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from '@tanstack/react-query';

import type { Error, FavoritesBody, Movie, User } from '../model';

import favoritesGETMutator from '../../lib/mutator';
import favoritesPOSTMutator from '../../lib/mutator';
import favoritesMovieIdDELETEMutator from '../../lib/mutator';

export type favoritesGETResponse200 = {
	data: Movie[];
	status: 200;
};

export type favoritesGETResponseSuccess = favoritesGETResponse200 & {
	headers: Headers;
};
export type favoritesGETResponse = favoritesGETResponseSuccess;

export const getFavoritesGETUrl = () => {
	return `/favorites`;
};

/**
 * @summary Получение избранных фильмов
 */
export const favoritesGET = async (
	options?: RequestInit,
): Promise<favoritesGETResponse> => {
	return favoritesGETMutator<favoritesGETResponse>(getFavoritesGETUrl(), {
		...options,
		method: 'GET',
	});
};

export const getFavoritesGETQueryKey = () => {
	return [`/favorites`] as const;
};

export const getFavoritesGETQueryOptions = <
	TData = Awaited<ReturnType<typeof favoritesGET>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof favoritesGET>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getFavoritesGETQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof favoritesGET>>> = ({
		signal,
	}) => favoritesGET({ signal });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof favoritesGET>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FavoritesGETQueryResult = NonNullable<
	Awaited<ReturnType<typeof favoritesGET>>
>;
export type FavoritesGETQueryError = unknown;

export function useFavoritesGET<
	TData = Awaited<ReturnType<typeof favoritesGET>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof favoritesGET>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof favoritesGET>>,
					TError,
					Awaited<ReturnType<typeof favoritesGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesGET<
	TData = Awaited<ReturnType<typeof favoritesGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof favoritesGET>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof favoritesGET>>,
					TError,
					Awaited<ReturnType<typeof favoritesGET>>
				>,
				'initialData'
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFavoritesGET<
	TData = Awaited<ReturnType<typeof favoritesGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof favoritesGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получение избранных фильмов
 */

export function useFavoritesGET<
	TData = Awaited<ReturnType<typeof favoritesGET>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof favoritesGET>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getFavoritesGETQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type favoritesPOSTResponse200 = {
	data: User;
	status: 200;
};

export type favoritesPOSTResponse400 = {
	data: Error;
	status: 400;
};

export type favoritesPOSTResponseSuccess = favoritesPOSTResponse200 & {
	headers: Headers;
};
export type favoritesPOSTResponseError = favoritesPOSTResponse400 & {
	headers: Headers;
};

export type favoritesPOSTResponse =
	| favoritesPOSTResponseSuccess
	| favoritesPOSTResponseError;

export const getFavoritesPOSTUrl = () => {
	return `/favorites`;
};

/**
 * @summary Добавление фильма в избранное
 */
export const favoritesPOST = async (
	favoritesBody?: FavoritesBody,
	options?: RequestInit,
): Promise<favoritesPOSTResponse> => {
	const formUrlEncoded = new URLSearchParams();
	if (favoritesBody?.id !== undefined) {
		formUrlEncoded.append(`id`, favoritesBody.id);
	}

	return favoritesPOSTMutator<favoritesPOSTResponse>(getFavoritesPOSTUrl(), {
		...options,
		method: 'POST',
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options?.headers,
		},
		body: formUrlEncoded,
	});
};

export const getFavoritesPOSTMutationOptions = <
	TError = Error,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof favoritesPOST>>,
		TError,
		{ data?: FavoritesBody },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof favoritesPOST>>,
	TError,
	{ data?: FavoritesBody },
	TContext
> => {
	const mutationKey = ['favoritesPOST'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof favoritesPOST>>,
		{ data?: FavoritesBody }
	> = (props) => {
		const { data } = props ?? {};

		return favoritesPOST(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type FavoritesPOSTMutationResult = NonNullable<
	Awaited<ReturnType<typeof favoritesPOST>>
>;
export type FavoritesPOSTMutationBody = FavoritesBody | undefined;
export type FavoritesPOSTMutationError = Error;

/**
 * @summary Добавление фильма в избранное
 */
export const useFavoritesPOST = <TError = Error, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof favoritesPOST>>,
			TError,
			{ data?: FavoritesBody },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof favoritesPOST>>,
	TError,
	{ data?: FavoritesBody },
	TContext
> => {
	return useMutation(getFavoritesPOSTMutationOptions(options), queryClient);
};
export type favoritesMovieIdDELETEResponse200 = {
	data: User;
	status: 200;
};

export type favoritesMovieIdDELETEResponseSuccess =
	favoritesMovieIdDELETEResponse200 & {
		headers: Headers;
	};
export type favoritesMovieIdDELETEResponse =
	favoritesMovieIdDELETEResponseSuccess;

export const getFavoritesMovieIdDELETEUrl = (movieId: number) => {
	return `/favorites/${movieId}`;
};

/**
 * @summary Удаление фильма из избранного
 */
export const favoritesMovieIdDELETE = async (
	movieId: number,
	options?: RequestInit,
): Promise<favoritesMovieIdDELETEResponse> => {
	return favoritesMovieIdDELETEMutator<favoritesMovieIdDELETEResponse>(
		getFavoritesMovieIdDELETEUrl(movieId),
		{
			...options,
			method: 'DELETE',
		},
	);
};

export const getFavoritesMovieIdDELETEMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof favoritesMovieIdDELETE>>,
		TError,
		{ movieId: number },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof favoritesMovieIdDELETE>>,
	TError,
	{ movieId: number },
	TContext
> => {
	const mutationKey = ['favoritesMovieIdDELETE'];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			'mutationKey' in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof favoritesMovieIdDELETE>>,
		{ movieId: number }
	> = (props) => {
		const { movieId } = props ?? {};

		return favoritesMovieIdDELETE(movieId);
	};

	return { mutationFn, ...mutationOptions };
};

export type FavoritesMovieIdDELETEMutationResult = NonNullable<
	Awaited<ReturnType<typeof favoritesMovieIdDELETE>>
>;

export type FavoritesMovieIdDELETEMutationError = unknown;

/**
 * @summary Удаление фильма из избранного
 */
export const useFavoritesMovieIdDELETE = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof favoritesMovieIdDELETE>>,
			TError,
			{ movieId: number },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof favoritesMovieIdDELETE>>,
	TError,
	{ movieId: number },
	TContext
> => {
	return useMutation(
		getFavoritesMovieIdDELETEMutationOptions(options),
		queryClient,
	);
};
