/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { Movie, User } from '../model';

export const getFavoritesGETResponseMock = (): Movie[] =>
	Array.from(
		{ length: faker.number.int({ min: 1, max: 10 }) },
		(_, i) => i + 1,
	).map(() => ({
		id: faker.helpers.arrayElement([faker.number.int(), undefined]),
		title: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		originalTitle: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		language: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		releaseYear: faker.helpers.arrayElement([faker.number.int(), undefined]),
		releaseDate: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		genres: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			undefined,
		]),
		plot: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		runtime: faker.helpers.arrayElement([faker.number.int(), undefined]),
		budget: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		revenue: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		homepage: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		status: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		posterUrl: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		backdropUrl: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		trailerUrl: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		trailerYouTubeId: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		tmdbRating: faker.helpers.arrayElement([faker.number.int(), undefined]),
		searchL: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		keywords: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			undefined,
		]),
		countriesOfOrigin: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			undefined,
		]),
		languages: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			undefined,
		]),
		cast: faker.helpers.arrayElement([
			Array.from(
				{ length: faker.number.int({ min: 1, max: 10 }) },
				(_, i) => i + 1,
			).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
			undefined,
		]),
		director: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		production: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
		awardsSummary: faker.helpers.arrayElement([
			faker.string.alpha({ length: { min: 10, max: 20 } }),
			undefined,
		]),
	}));

export const getFavoritesPOSTResponseMock = (
	overrideResponse: Partial<Extract<User, object>> = {},
): User => ({
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	surname: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	email: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	favorites: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
		undefined,
	]),
	...overrideResponse,
});

export const getFavoritesMovieIdDELETEResponseMock = (
	overrideResponse: Partial<Extract<User, object>> = {},
): User => ({
	name: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	surname: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	email: faker.helpers.arrayElement([
		faker.string.alpha({ length: { min: 10, max: 20 } }),
		undefined,
	]),
	favorites: faker.helpers.arrayElement([
		Array.from(
			{ length: faker.number.int({ min: 1, max: 10 }) },
			(_, i) => i + 1,
		).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
		undefined,
	]),
	...overrideResponse,
});

export const getFavoritesGETMockHandler = (
	overrideResponse?:
		| Movie[]
		| ((
				info: Parameters<Parameters<typeof http.get>[1]>[0],
		  ) => Promise<Movie[]> | Movie[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		'*/favorites',
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getFavoritesGETResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getFavoritesPOSTMockHandler = (
	overrideResponse?:
		| User
		| ((
				info: Parameters<Parameters<typeof http.post>[1]>[0],
		  ) => Promise<User> | User),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		'*/favorites',
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getFavoritesPOSTResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getFavoritesMovieIdDELETEMockHandler = (
	overrideResponse?:
		| User
		| ((
				info: Parameters<Parameters<typeof http.delete>[1]>[0],
		  ) => Promise<User> | User),
	options?: RequestHandlerOptions,
) => {
	return http.delete(
		'*/favorites/:movieId',
		async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === 'function'
						? await overrideResponse(info)
						: overrideResponse
					: getFavoritesMovieIdDELETEResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};
export const getFavoritesMock = () => [
	getFavoritesGETMockHandler(),
	getFavoritesPOSTMockHandler(),
	getFavoritesMovieIdDELETEMockHandler(),
];
