/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */

export * from './apiResponse';
export * from './authInfo';
export * from './error';
export * from './favoritesBody';
export * from './movie';
export * from './movieGETParams';
export * from './registerData';
export * from './successfulResult';
export * from './user';
export * from './userArrayBody';
