/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */

export interface Movie {
	id?: number;
	title?: string;
	originalTitle?: string;
	language?: string;
	releaseYear?: number;
	releaseDate?: string;
	genres?: string[];
	plot?: string;
	runtime?: number;
	budget?: string;
	revenue?: string;
	homepage?: string;
	status?: string;
	posterUrl?: string;
	backdropUrl?: string;
	trailerUrl?: string;
	trailerYouTubeId?: string;
	tmdbRating?: number;
	searchL?: string;
	keywords?: string[];
	countriesOfOrigin?: string[];
	languages?: string[];
	cast?: string[];
	director?: string;
	production?: string;
	awardsSummary?: string;
}
