/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Movie API 1.0
 * Данная API предоставляет набор URL, делая запросы на которые Вы получите данные, необходимые для выполнения дипломной работы.
 * OpenAPI spec version: 1.0.0
 */

export interface SuccessfulResult {
	result: boolean;
}
